### ISSUE TITLE
charm is not resilient to transient errors

### ISSUE THREAD

**Issue by nishant-dash** [canonical/charm-juju-backup-all#88]
if there is a network blip or cut in the connection for whatever reason, the backups can fail. Then when you run the backup again when things are ok, its fine.

the charm should be able to retry backups in case of failures. Perhaps a temporal based workflow could be beneficial rather than implementing retry logic, etc...

**Comment by nishant-dash** [comment]
further more, when runnning the action later succesfully, `/var/lib/jujubackupall/auto_backup_results.json` isnt updated so the alert for failed backup stays until you copy paste the output from the action into that file

**Comment by nishant-dash** [comment]
additionally I see
```
    "error_reason": "JujuTimeoutError: Task 'mysqldump' timed out (timeout=600)."
```

but 
```yaml
  timeout:
    default: 60
    description: |
      Timeout in seconds for long running commands. This setting is used for
      each task and not for the whole backup operation.
    source: user
    type: int
    value: 3600
```
